### PR TITLE
[github] add templates for issues and PR

### PR DESCRIPTION
**Pull request by lgrd**
Adapted templates for pgr. It's all about issues and PR.

### CODE REVIEW

**Review by azarz — APPROVED** [review]

**Comment by Guts** [comment]
Why not using issue form instead of markdown? It's really better in terms of user-friendy reporting workflow: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Examples:

- https://github.com/Guts/qgis-deployment-cli/issues/new/choose
- https://github.com/squidfunk/mkdocs-material/issues/new/choose
- https://github.com/geotribu/website/issues/new?assignees=aurelienchaumet%2Cguts%2Cigeofr&labels=contribution+externe%2Crdp%2Ctriage&projects=&template=RDP_NEWS.yml

**Comment by lgrd** [comment]
> Why not using issue form instead of markdown? It's really better in terms of user-friendy reporting workflow: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
> 
> Examples:
> 
>     * https://github.com/Guts/qgis-deployment-cli/issues/new/choose
> 
>     * https://github.com/squidfunk/mkdocs-material/issues/new/choose
> 
>     * https://github.com/geotribu/website/issues/new?assignees=aurelienchaumet%2Cguts%2Cigeofr&labels=contribution+externe%2Crdp%2Ctriage&projects=&template=RDP_NEWS.yml

It looks like a good idea ;) We didn't know this syntax.

**Comment by lgrd** [comment]
@Guts, we will wait for a stable version of this feature because : 
- It's a beta, 
- and this [article about errors](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms) is not a friendly one. 
But because, it is a good idea for user-friendly issues, I will put it in the roadmap. ;)

**Comment by Guts** [comment]
Ups bad button move, sorry!

> and this [article about errors](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms) is not a friendly one.

Don't be so shy, auto-completion and validator are both integrated to GitHub web editor or VS Code extension!

Well, I stay tuned to see the next PRs/issues templates evolution! :wink:

**Pull request merged**
